apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-deployment
  labels:
    app: translation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation
  template:
    metadata:
      labels:
        app: translation
    spec:
      containers:
      - name: translation-container
        image: [aws_account_id].dkr.ecr.us-west-2.amazonaws.com/translation-front:1.0-SNAPSHOT
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: 250m

---
# Open NodePort - optional, but helpful for debugging load balancer
apiVersion: v1
kind: Service
metadata:
  name: system-translation
spec:
  type: NodePort
  selector:
    app: translation
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: lb-translation
spec:
  type: LoadBalancer
  selector:
    app: translation
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8501
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8501
  - name: test
    protocol: TCP
    port: 81
    targetPort: 8501